services:
  wazuh.indexer:
    image: opensearchproject/opensearch:2.11.0
    hostname: wazuh.indexer
    container_name: wazuh.indexer
    restart: always
    environment:
      - "network.host=0.0.0.0"
      - "discovery.type=single-node"
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - wazuh-indexer-data:/usr/share/opensearch/data
    networks:
      - soc_net

  wazuh.manager:
    image: wazuh/wazuh-manager:4.7.2
    hostname: wazuh.manager
    container_name: wazuh.manager
    restart: always
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - INDEXER_URL=http://wazuh.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=admin
      - FILEBEAT_SSL_VERIFICATION_MODE=none
    volumes:
      - wazuh-manager-logs:/var/ossec/logs
    networks:
      - soc_net

  wazuh.dashboard:
    image: opensearchproject/opensearch-dashboards:2.11.0
    hostname: wazuh.dashboard
    container_name: wazuh.dashboard
    restart: always
    ports:
      - "443:5601"
    environment:
      - "OPENSEARCH_HOSTS=http://wazuh.indexer:9200"
      - "DISABLE_SECURITY_DASHBOARD_PLUGIN=true"
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    depends_on:
      - wazuh.manager
    networks:
      - soc_net

  soc-monitor:
    build:
      context: ./soc-monitor
    container_name: soc.monitor
    ports:
      - "8080:5000"
    volumes:
      - wazuh-manager-logs:/app/logs:ro
    depends_on:
      - wazuh.manager
    networks:
      - soc_net

  wazuh.agent:
    build:
      context: ./config/wazuh_agent
      dockerfile: Dockerfile
    hostname: wazuh.agent.local
    container_name: wazuh.agent
    restart: always
    privileged: true
    environment:
      - WAZUH_MANAGER=wazuh.manager
      - WAZUH_AGENT_GROUP=default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/auth.log:/var/log/auth.log:ro
      - /var/log/syslog:/var/log/syslog:ro
    depends_on:
      - wazuh.manager
    networks:
      - soc_net

volumes:
  wazuh-indexer-data:
  wazuh-manager-logs:


networks:
  soc_net:
    driver: bridge
